[build-system]
requires = [
    "setuptools>=54.1.3",
    "wheel>=0.36.2",
    "oldest-supported-numpy",
    "cython~=0.29.26 ; platform_system != 'Windows'",
    "ultranest~=3.3.3 ; platform_system != 'Windows'",
]
build-backend = "setuptools.build_meta"

