name: tess
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.12.0
  - appnope=0.1.2
  - astor=0.8.1
  - backcall=0.2.0
  - blas=1.0
  - c-ares=1.17.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - coverage=5.5
  - decorator=4.4.2
  - entrypoints=0.4
  - gast=0.2.2
  - google-pasta=0.2.0
  - grpcio=1.36.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - importlib-metadata=3.7.3
  - intel-openmp=2019.4
  - ipykernel=5.5.5
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.3
  - jupyter_client=5.3.4
  - jupyter_core=4.5.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=15.0.7
  - libffi=3.3
  - libgfortran=3.0.1
  - liblapack=3.9.0
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - llvm-openmp=16.0.0
  - markdown=3.3.4
  - markupsafe=1.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.2
  - numpy=1.21.6
  - openssl=1.1.1t
  - opt_einsum=3.1.0
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - prompt-toolkit=3.0.17
  - protobuf=3.14.0
  - ptyprocess=0.7.0
  - pygments=2.8.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pyzmq=19.0.2
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.2
  - tbb=2021.8.0
  - tensorboard=1.15.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - termcolor=1.1.0
  - tk=8.6.10
  - traitlets=5.0.5
  - typing_extensions=4.5.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wrapt=1.12.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - pip:
    - asteval==0.9.26
    - astroalign==2.4.1
    - astropy==4.3.1
    - astroquery==0.4.2
    - autograd==1.3
    - barycorrpy==0.4.4
    - batman-package==2.4.8
    - beautifulsoup4==4.9.3
    - bleach==5.0.0
    - bokeh==2.4.2
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - colorcet==3.0.0
    - configparser==5.2.0
    - corner==2.2.1
    - cycler==0.10.0
    - cython==0.29.28
    - dynesty==1.2.2
    - eleanor==2.0.2
    - emcee==3.1.1
    - exotic>=1.10.0
    - fonttools==4.33.2
    - future==0.18.2
    - holoviews==1.15.4
    - html5lib==1.1
    - idna==2.10
    - imageio==2.18.0
    - imreg-dft==2.0.0
    - joblib==1.0.1
    - jplephem==2.17
    - keyring==23.0.0
    - kiwisolver==1.3.1
    - ldtk==1.7.0
    - lightkurve==2.0.6
    - llvmlite==0.39.1
    - lmfit==1.0.3
    - matplotlib==3.5.1
    - memoization==0.3.2
    - networkx==2.6.3
    - numba==0.56.4
    - packaging==21.3
    - pandas==1.3.5
    - panel==0.13.1
    - param==1.12.1
    - patsy==0.5.2
    - photutils==1.1.0
    - pillow==9.1.0
    - pyct==0.4.8
    - pyerfa==2.0.0.1
    - pylightcurve==4.0.1
    - pylightcurve-torch==1.0.0
    - pyparsing==3.0.0b2
    - python-version==0.0.2
    - pyviz-comms==2.2.0
    - pyvo==1.2.1
    - pywavelets==1.3.0
    - pyyaml==5.4.1
    - requests==2.28.2
    - scikit-image==0.19.2
    - scikit-learn==0.24.1
    - scipy==1.7.3
    - semantic-version==2.9.0
    - sep==1.2.0
    - soupsieve==2.2.1
    - statsmodels==0.13.2
    - tenacity==8.2.0
    - threadpoolctl==2.1.0
    - tifffile==2021.11.2
    - torch==1.8.0
    - tornado==6.1
    - tqdm==4.59.0
    - transitleastsquares==1.0.31
    - typing-extensions==4.2.0
    - ultranest==3.5.7
    - uncertainties==3.1.5
    - urllib3==1.26.4
    - wheel==0.36.2
    - wotan==1.9
